// SPDX-License-Identifier: MIT
// Telescope Connection Manager
// Copyright (c) 2023 Tim Dettmar

#include "tcm_errno.h"
#include <stdio.h>

int tcm_err_to_sys(unsigned int tcm_errno) {
    switch (tcm_errno) {
        case TCM_EPERM:
            return TCM_SYS_EPERM;
        case TCM_ENOENT:
            return TCM_SYS_ENOENT;
        case TCM_ESRCH:
            return TCM_SYS_ESRCH;
        case TCM_EINTR:
            return TCM_SYS_EINTR;
        case TCM_EIO:
            return TCM_SYS_EIO;
        case TCM_ENXIO:
            return TCM_SYS_ENXIO;
        case TCM_ENOEXEC:
            return TCM_SYS_ENOEXEC;
        case TCM_EBADF:
            return TCM_SYS_EBADF;
        case TCM_ECHILD:
            return TCM_SYS_ECHILD;
        case TCM_EDEADLK:
            return TCM_SYS_EDEADLK;
        case TCM_ENOMEM:
            return TCM_SYS_ENOMEM;
        case TCM_EACCES:
            return TCM_SYS_EACCES;
        case TCM_EFAULT:
            return TCM_SYS_EFAULT;
        case TCM_ENOTBLK:
            return TCM_SYS_ENOTBLK;
        case TCM_EBUSY:
            return TCM_SYS_EBUSY;
        case TCM_EEXIST:
            return TCM_SYS_EEXIST;
        case TCM_EXDEV:
            return TCM_SYS_EXDEV;
        case TCM_ENODEV:
            return TCM_SYS_ENODEV;
        case TCM_ENOTDIR:
            return TCM_SYS_ENOTDIR;
        case TCM_EISDIR:
            return TCM_SYS_EISDIR;
        case TCM_EINVAL:
            return TCM_SYS_EINVAL;
        case TCM_ENFILE:
            return TCM_SYS_ENFILE;
        case TCM_EMFILE:
            return TCM_SYS_EMFILE;
        case TCM_ENOTTY:
            return TCM_SYS_ENOTTY;
        case TCM_ETXTBSY:
            return TCM_SYS_ETXTBSY;
        case TCM_EFBIG:
            return TCM_SYS_EFBIG;
        case TCM_ENOSPC:
            return TCM_SYS_ENOSPC;
        case TCM_ESPIPE:
            return TCM_SYS_ESPIPE;
        case TCM_EROFS:
            return TCM_SYS_EROFS;
        case TCM_EMLINK:
            return TCM_SYS_EMLINK;
        case TCM_EPIPE:
            return TCM_SYS_EPIPE;
        case TCM_EDOM:
            return TCM_SYS_EDOM;
        case TCM_ERANGE:
            return TCM_SYS_ERANGE;
        case TCM_EAGAIN:
            return TCM_SYS_EAGAIN;
        case TCM_EINPROGRESS:
            return TCM_SYS_EINPROGRESS;
        case TCM_EALREADY:
            return TCM_SYS_EALREADY;
        case TCM_ENOTSOCK:
            return TCM_SYS_ENOTSOCK;
        case TCM_EDESTADDRREQ:
            return TCM_SYS_EDESTADDRREQ;
        case TCM_EMSGSIZE:
            return TCM_SYS_EMSGSIZE;
        case TCM_EPROTOTYPE:
            return TCM_SYS_EPROTOTYPE;
        case TCM_ENOPROTOOPT:
            return TCM_SYS_ENOPROTOOPT;
        case TCM_EPROTONOSUPPORT:
            return TCM_SYS_EPROTONOSUPPORT;
        case TCM_ESOCKTNOSUPPORT:
            return TCM_SYS_ESOCKTNOSUPPORT;
        case TCM_EOPNOTSUPP:
            return TCM_SYS_EOPNOTSUPP;
        case TCM_EPFNOSUPPORT:
            return TCM_SYS_EPFNOSUPPORT;
        case TCM_EAFNOSUPPORT:
            return TCM_SYS_EAFNOSUPPORT;
        case TCM_EADDRINUSE:
            return TCM_SYS_EADDRINUSE;
        case TCM_EADDRNOTAVAIL:
            return TCM_SYS_EADDRNOTAVAIL;
        case TCM_ENETDOWN:
            return TCM_SYS_ENETDOWN;
        case TCM_ENETUNREACH:
            return TCM_SYS_ENETUNREACH;
        case TCM_ENETRESET:
            return TCM_SYS_ENETRESET;
        case TCM_ECONNABORTED:
            return TCM_SYS_ECONNABORTED;
        case TCM_ECONNRESET:
            return TCM_SYS_ECONNRESET;
        case TCM_ENOBUFS:
            return TCM_SYS_ENOBUFS;
        case TCM_EISCONN:
            return TCM_SYS_EISCONN;
        case TCM_ENOTCONN:
            return TCM_SYS_ENOTCONN;
        case TCM_ESHUTDOWN:
            return TCM_SYS_ESHUTDOWN;
        case TCM_ETOOMANYREFS:
            return TCM_SYS_ETOOMANYREFS;
        case TCM_ETIMEDOUT:
            return TCM_SYS_ETIMEDOUT;
        case TCM_ECONNREFUSED:
            return TCM_SYS_ECONNREFUSED;
        case TCM_ELOOP:
            return TCM_SYS_ELOOP;
        case TCM_ENAMETOOLONG:
            return TCM_SYS_ENAMETOOLONG;
        case TCM_EHOSTDOWN:
            return TCM_SYS_EHOSTDOWN;
        case TCM_EHOSTUNREACH:
            return TCM_SYS_EHOSTUNREACH;
        case TCM_ENOTEMPTY:
            return TCM_SYS_ENOTEMPTY;
        case TCM_EPROCLIM:
            return TCM_SYS_EPROCLIM;
        case TCM_EUSERS:
            return TCM_SYS_EUSERS;
        case TCM_EDQUOT:
            return TCM_SYS_EDQUOT;
        case TCM_ESTALE:
            return TCM_SYS_ESTALE;
        case TCM_EREMOTE:
            return TCM_SYS_EREMOTE;
        case TCM_EBADRPC:
            return TCM_SYS_EBADRPC;
        case TCM_ERPCMISMATCH:
            return TCM_SYS_ERPCMISMATCH;
        case TCM_EPROGUNAVAIL:
            return TCM_SYS_EPROGUNAVAIL;
        case TCM_EPROGMISMATCH:
            return TCM_SYS_EPROGMISMATCH;
        case TCM_EPROCUNAVAIL:
            return TCM_SYS_EPROCUNAVAIL;
        case TCM_ENOLCK:
            return TCM_SYS_ENOLCK;
        case TCM_ENOSYS:
            return TCM_SYS_ENOSYS;
        case TCM_EFTYPE:
            return TCM_SYS_EFTYPE;
        case TCM_EAUTH:
            return TCM_SYS_EAUTH;
        case TCM_ENEEDAUTH:
            return TCM_SYS_ENEEDAUTH;
        case TCM_EIDRM:
            return TCM_SYS_EIDRM;
        case TCM_ENOMSG:
            return TCM_SYS_ENOMSG;
        case TCM_EOVERFLOW:
            return TCM_SYS_EOVERFLOW;
        case TCM_ECANCELED:
            return TCM_SYS_ECANCELED;
        case TCM_EILSEQ:
            return TCM_SYS_EILSEQ;
        case TCM_ENOATTR:
            return TCM_SYS_ENOATTR;
        case TCM_EDOOFUS:
            return TCM_SYS_EDOOFUS;
        case TCM_EBADMSG:
            return TCM_SYS_EBADMSG;
        case TCM_EMULTIHOP:
            return TCM_SYS_EMULTIHOP;
        case TCM_ENOLINK:
            return TCM_SYS_ENOLINK;
        case TCM_EPROTO:
            return TCM_SYS_EPROTO;
        case TCM_ENOTCAPABLE:
            return TCM_SYS_ENOTCAPABLE;
        case TCM_ECAPMODE:
            return TCM_SYS_ECAPMODE;
        case TCM_ENOTRECOVERABLE:
            return TCM_SYS_ENOTRECOVERABLE;
        case TCM_EOWNERDEAD:
            return TCM_SYS_EOWNERDEAD;
        case TCM_EINTEGRITY:
            return TCM_SYS_EINTEGRITY;
        default:
            return -1;
    }
}

int tcm_sys_to_err(unsigned int sys_errno) {
    switch (sys_errno) {
        case TCM_SYS_EPERM:
            return TCM_EPERM;
        case TCM_SYS_ENOENT:
            return TCM_ENOENT;
        case TCM_SYS_ESRCH:
            return TCM_ESRCH;
        case TCM_SYS_EINTR:
            return TCM_EINTR;
        case TCM_SYS_EIO:
            return TCM_EIO;
        case TCM_SYS_ENXIO:
            return TCM_ENXIO;
        case TCM_SYS_ENOEXEC:
            return TCM_ENOEXEC;
        case TCM_SYS_EBADF:
            return TCM_EBADF;
        case TCM_SYS_ECHILD:
            return TCM_ECHILD;
        case TCM_SYS_EDEADLK:
            return TCM_EDEADLK;
        case TCM_SYS_ENOMEM:
            return TCM_ENOMEM;
        case TCM_SYS_EACCES:
            return TCM_EACCES;
        case TCM_SYS_EFAULT:
            return TCM_EFAULT;
        case TCM_SYS_ENOTBLK:
            return TCM_ENOTBLK;
        case TCM_SYS_EBUSY:
            return TCM_EBUSY;
        case TCM_SYS_EEXIST:
            return TCM_EEXIST;
        case TCM_SYS_EXDEV:
            return TCM_EXDEV;
        case TCM_SYS_ENODEV:
            return TCM_ENODEV;
        case TCM_SYS_ENOTDIR:
            return TCM_ENOTDIR;
        case TCM_SYS_EISDIR:
            return TCM_EISDIR;
        case TCM_SYS_EINVAL:
            return TCM_EINVAL;
        case TCM_SYS_ENFILE:
            return TCM_ENFILE;
        case TCM_SYS_EMFILE:
            return TCM_EMFILE;
        case TCM_SYS_ENOTTY:
            return TCM_ENOTTY;
        case TCM_SYS_ETXTBSY:
            return TCM_ETXTBSY;
        case TCM_SYS_EFBIG:
            return TCM_EFBIG;
        case TCM_SYS_ENOSPC:
            return TCM_ENOSPC;
        case TCM_SYS_ESPIPE:
            return TCM_ESPIPE;
        case TCM_SYS_EROFS:
            return TCM_EROFS;
        case TCM_SYS_EMLINK:
            return TCM_EMLINK;
        case TCM_SYS_EPIPE:
            return TCM_EPIPE;
        case TCM_SYS_EDOM:
            return TCM_EDOM;
        case TCM_SYS_ERANGE:
            return TCM_ERANGE;
        case TCM_SYS_EAGAIN:
            return TCM_EAGAIN;
        case TCM_SYS_EINPROGRESS:
            return TCM_EINPROGRESS;
        case TCM_SYS_EALREADY:
            return TCM_EALREADY;
        case TCM_SYS_ENOTSOCK:
            return TCM_ENOTSOCK;
        case TCM_SYS_EDESTADDRREQ:
            return TCM_EDESTADDRREQ;
        case TCM_SYS_EMSGSIZE:
            return TCM_EMSGSIZE;
        case TCM_SYS_EPROTOTYPE:
            return TCM_EPROTOTYPE;
        case TCM_SYS_ENOPROTOOPT:
            return TCM_ENOPROTOOPT;
        case TCM_SYS_EPROTONOSUPPORT:
            return TCM_EPROTONOSUPPORT;
        case TCM_SYS_ESOCKTNOSUPPORT:
            return TCM_ESOCKTNOSUPPORT;
        case TCM_SYS_EOPNOTSUPP:
            return TCM_EOPNOTSUPP;
        case TCM_SYS_EPFNOSUPPORT:
            return TCM_EPFNOSUPPORT;
        case TCM_SYS_EAFNOSUPPORT:
            return TCM_EAFNOSUPPORT;
        case TCM_SYS_EADDRINUSE:
            return TCM_EADDRINUSE;
        case TCM_SYS_EADDRNOTAVAIL:
            return TCM_EADDRNOTAVAIL;
        case TCM_SYS_ENETDOWN:
            return TCM_ENETDOWN;
        case TCM_SYS_ENETUNREACH:
            return TCM_ENETUNREACH;
        case TCM_SYS_ENETRESET:
            return TCM_ENETRESET;
        case TCM_SYS_ECONNABORTED:
            return TCM_ECONNABORTED;
        case TCM_SYS_ECONNRESET:
            return TCM_ECONNRESET;
        case TCM_SYS_ENOBUFS:
            return TCM_ENOBUFS;
        case TCM_SYS_EISCONN:
            return TCM_EISCONN;
        case TCM_SYS_ENOTCONN:
            return TCM_ENOTCONN;
        case TCM_SYS_ESHUTDOWN:
            return TCM_ESHUTDOWN;
        case TCM_SYS_ETOOMANYREFS:
            return TCM_ETOOMANYREFS;
        case TCM_SYS_ETIMEDOUT:
            return TCM_ETIMEDOUT;
        case TCM_SYS_ECONNREFUSED:
            return TCM_ECONNREFUSED;
        case TCM_SYS_ELOOP:
            return TCM_ELOOP;
        case TCM_SYS_ENAMETOOLONG:
            return TCM_ENAMETOOLONG;
        case TCM_SYS_EHOSTDOWN:
            return TCM_EHOSTDOWN;
        case TCM_SYS_EHOSTUNREACH:
            return TCM_EHOSTUNREACH;
        case TCM_SYS_ENOTEMPTY:
            return TCM_ENOTEMPTY;
        case TCM_SYS_EPROCLIM:
            return TCM_EPROCLIM;
        case TCM_SYS_EUSERS:
            return TCM_EUSERS;
        case TCM_SYS_EDQUOT:
            return TCM_EDQUOT;
        case TCM_SYS_ESTALE:
            return TCM_ESTALE;
        case TCM_SYS_EREMOTE:
            return TCM_EREMOTE;
        case TCM_SYS_EBADRPC:
            return TCM_EBADRPC;
        case TCM_SYS_ERPCMISMATCH:
            return TCM_ERPCMISMATCH;
        case TCM_SYS_EPROGUNAVAIL:
            return TCM_EPROGUNAVAIL;
        case TCM_SYS_EPROGMISMATCH:
            return TCM_EPROGMISMATCH;
        case TCM_SYS_EPROCUNAVAIL:
            return TCM_EPROCUNAVAIL;
        case TCM_SYS_ENOLCK:
            return TCM_ENOLCK;
        case TCM_SYS_ENOSYS:
            return TCM_ENOSYS;
        case TCM_SYS_EFTYPE:
            return TCM_EFTYPE;
        case TCM_SYS_EAUTH:
            return TCM_EAUTH;
        case TCM_SYS_ENEEDAUTH:
            return TCM_ENEEDAUTH;
        case TCM_SYS_EIDRM:
            return TCM_EIDRM;
        case TCM_SYS_ENOMSG:
            return TCM_ENOMSG;
        case TCM_SYS_EOVERFLOW:
            return TCM_EOVERFLOW;
        case TCM_SYS_ECANCELED:
            return TCM_ECANCELED;
        case TCM_SYS_EILSEQ:
            return TCM_EILSEQ;
        case TCM_SYS_ENOATTR:
            return TCM_ENOATTR;
        case TCM_SYS_EDOOFUS:
            return TCM_EDOOFUS;
        case TCM_SYS_EBADMSG:
            return TCM_EBADMSG;
        case TCM_SYS_EMULTIHOP:
            return TCM_EMULTIHOP;
        case TCM_SYS_ENOLINK:
            return TCM_ENOLINK;
        case TCM_SYS_EPROTO:
            return TCM_EPROTO;
        case TCM_SYS_ENOTCAPABLE:
            return TCM_ENOTCAPABLE;
        case TCM_SYS_ECAPMODE:
            return TCM_ECAPMODE;
        case TCM_SYS_ENOTRECOVERABLE:
            return TCM_ENOTRECOVERABLE;
        case TCM_SYS_EOWNERDEAD:
            return TCM_EOWNERDEAD;
        case TCM_SYS_EINTEGRITY:
            return TCM_EINTEGRITY;
        default:
            return -1;
    }
}

const char * tcm_err_string(unsigned int err) {
    static char tmp_err[32];
    switch (err) {
        case TCM_ERR_INVALID_ADDRESS:
            return "Invalid network address";
        case TCM_ERR_INVALID_FABRIC_VER:
            return "Invalid or mismatched Libfabric version";
        case TCM_ERR_VERSION_MISMATCH:
            return "TCM API version mismatch";
        case TCM_ERR_UNSPECIFIED:
            return "Unspecified error";
        default:
            if (err < FI_ERRNO_OFFSET)
                return strerror(err);
            if (err < TCM_ERR_UNSPECIFIED)
                return fi_strerror(err);
            snprintf(tmp_err, 32, "Unknown error %d", err);
            return tmp_err;
    }
}